export type PaletteTokens =
  | "cyan"
  | "orange"
  | "pink"
  | "primary01"
  | "primary02"
  | "primary03"
  | "primary04"
  | "primaryDisable"
  | "surface01"
  | "surface02"
  | "surfaceHover01"
  | "surfaceHover02"
  | "surfaceDisable"
  | "bg01"
  | "primary"
  | "primaryShade01"
  | "primaryShade02"
  | "primaryText"
  | "primaryHover"
  | "primaryTint01"
  | "primaryTint02"
  | "secondary"
  | "secondaryShade01"
  | "secondaryShade02"
  | "secondaryText"
  | "secondaryHover"
  | "secondaryTint01"
  | "secondaryTint02"
  | "positive"
  | "positiveShade"
  | "positiveText"
  | "positiveTint01"
  | "positiveTint02"
  | "warning"
  | "warningShade01"
  | "warningText"
  | "warningTint01"
  | "danger"
  | "dangerShade01"
  | "dangerShade02"
  | "dangerDisable"
  | "dangerTint01"
  | "dangerTint02"
  | "dangerTint03";

export type PaletteObject = {
  [key in PaletteTokens]: string;
};
